from ultralytics import YOLO

path: "E:\Учеба\ВРЕМЕННОЕ\Object-Detection-YOLO\dataSet VisDrone" # train images (relative to 'path')  6471 images
train: "E:\Учеба\ВРЕМЕННОЕ\Object-Detection-YOLO\dataSet VisDrone\Val\images" # train images (relative to 'path')  6471 images
val: "E:\Учеба\ВРЕМЕННОЕ\Object-Detection-YOLO\dataSet VisDrone\"Val\images" # val images (relative to 'path')  548 images
test: "E:\Учеба\ВРЕМЕННОЕ\Object-Detection-YOLO\dataSet VisDrone\Test\images" # test images (optional)  1610 images

# Classes
names:
  0: pedestrian
  1: people
  2: bicycle
  3: car
  4: van
  5: truck
  6: tricycle
  7: awning-tricycle
  8: bus
  9: motor